In [2]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float, requires_grad=True,
                 device=device)
print(x)
print(x.shape)
print(x.device)
print(x.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
cpu
True


In [9]:
y = torch.empty(size=(2, 3))    # allocate the memory, the values are the original ones not necessarily zero
zero_y = torch.zeros((2, 3))    # create a tensor of all zeros
rand_y = torch.rand((3, 3))     # uniform distribution from 0 to 1
ones_y = torch.ones((2, 3))
print(ones_y)
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
I = torch.eye(3, 3, dtype=torch.float)  # identity matrix
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
arrange_y = torch.arange(start=0, end=8, step=1, dtype=torch.float)
arrange_y

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [11]:
y = torch.linspace(start=0, end=8, steps=9, dtype=torch.float)  # from start to end(include end), count number is "steps"
y

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [12]:
y = torch.empty(size=(2, 3), dtype=torch.float).normal_(mean=0, std=1)  # specify the mean and std, normal deploy
y

tensor([[-1.2012,  0.4575,  0.7854],
        [-0.1288,  0.9455, -1.2844]])

In [14]:
y = torch.empty(size=(2, 3), dtype=torch.float).uniform_(0, 1)  
y

tensor([[0.4376, 0.3490, 0.2101],
        [0.2567, 0.2733, 0.2738]])

In [15]:
y = torch.diag(torch.tensor([1, 2, 3])) # diag matrix, specify the elements in the main diagonal
y

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


# How to initialize and convert tensors to other types

In [16]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [18]:
x.bool()

tensor([False,  True,  True,  True])

In [19]:
x.float()   # 32bit float number

tensor([0., 1., 2., 3.])

In [20]:
x.long()    # 64int 

tensor([0, 1, 2, 3])

In [21]:
x.double() # 64float

tensor([0., 1., 2., 3.], dtype=torch.float64)

# array to tensor conversion and vice-versa

In [22]:
import numpy as np
x = np.zeros((2, 3))
tensor = torch.from_numpy(x)    # convert to tensor 
back_x = tensor.numpy()
tensor, back_x

(tensor([[0., 0., 0.],
         [0., 0., 0.]], dtype=torch.float64),
 array([[0., 0., 0.],
        [0., 0., 0.]]))