In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float, requires_grad=True,
                 device=device)
print(x)
print(x.shape)
print(x.device)
print(x.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
cpu
True


In [2]:
y = torch.empty(size=(2, 3))    # allocate the memory, the values are the original ones not necessarily zero
zero_y = torch.zeros((2, 3))    # create a tensor of all zeros
rand_y = torch.rand((3, 3))     # uniform distribution from 0 to 1
ones_y = torch.ones((2, 3))
print(ones_y)
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[-7.7915e+33,  1.4531e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [3]:
I = torch.eye(3, 3, dtype=torch.float)  # identity matrix
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [4]:
arrange_y = torch.arange(start=0, end=8, step=1, dtype=torch.float)
arrange_y

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [5]:
y = torch.linspace(start=0, end=8, steps=9, dtype=torch.float)  # from start to end(include end), count number is "steps"
y

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [6]:
y = torch.empty(size=(2, 3), dtype=torch.float).normal_(mean=0, std=1)  # specify the mean and std, normal deploy
y

tensor([[-0.3331,  0.4287,  0.1098],
        [ 0.0635, -1.1190, -0.1506]])

In [7]:
y = torch.empty(size=(2, 3), dtype=torch.float).uniform_(0, 1)  
y

tensor([[0.8939, 0.8007, 0.5679],
        [0.0439, 0.9103, 0.2866]])

In [8]:
y = torch.diag(torch.tensor([1, 2, 3])) # diag matrix, specify the elements in the main diagonal
y

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


# How to initialize and convert tensors to other types

In [9]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [10]:
x.bool()

tensor([False,  True,  True,  True])

In [11]:
x.float()   # 32bit float number

tensor([0., 1., 2., 3.])

In [12]:
x.long()    # 64int 

tensor([0, 1, 2, 3])

In [13]:
x.double() # 64float

tensor([0., 1., 2., 3.], dtype=torch.float64)

# array to tensor conversion and vice-versa

In [14]:
import numpy as np
x = np.zeros((2, 3))
tensor = torch.from_numpy(x)    # convert to tensor 
back_x = tensor.numpy()
tensor, back_x

(tensor([[0., 0., 0.],
         [0., 0., 0.]], dtype=torch.float64),
 array([[0., 0., 0.],
        [0., 0., 0.]]))