# Tensor math and comparison operation


In [1]:
import torch 

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

z = torch.empty(3)
torch.add(x, y, out=z)
z

tensor([10., 10., 10.])

In [4]:
z = torch.empty(3)
print(z)
z = x + y 
z

tensor([0., 0., 0.])


tensor([10, 10, 10])

In [3]:
z = torch.add(x, y)
z

tensor([10, 10, 10])

In [5]:
z = x - y
z

tensor([-8, -6, -4])

In [6]:
z = torch.true_divide(x, y) # divide elements in x correspondingly 
z

tensor([0.1111, 0.2500, 0.4286])

In [7]:
z = torch.true_divide(x, 2) # second parameter is int 
z

tensor([0.5000, 1.0000, 1.5000])

# inplace operation

In [9]:
t = torch.tensor([1, 2, 3])
t += x
print(t)
t.add_(x)
t

tensor([2, 4, 6])


tensor([3, 6, 9])

In [10]:
z = x.pow(2)
print(z)
z = x ** 2
z

tensor([1, 4, 9])


tensor([1, 4, 9])

In [11]:
z = x > 0
z

tensor([True, True, True])

# Matrix operation

In [17]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
y = torch.mm(x1, x2)    # matrix multiplication
print(y.shape, y)
y = x1.mm(x2)
y

torch.Size([2, 3]) tensor([[1.5647, 0.8168, 1.7942],
        [1.7839, 0.5029, 1.6849]])


tensor([[1.5647, 0.8168, 1.7942],
        [1.7839, 0.5029, 1.6849]])

In [22]:
mat_exp = torch.tensor([[1, 2], [3, 4]])
print(mat_exp.matrix_power(3))      # matrix_power 
print(mat_exp.mm(mat_exp).mm(mat_exp))

tensor([[ 37,  54],
        [ 81, 118]])
tensor([[ 37,  54],
        [ 81, 118]])


In [27]:
y = torch.tensor([9, 8, 7])
z = x * y # element wise multiply 
z

tensor([ 9, 16, 21])

In [28]:
z = torch.dot(x, y) # dot product, sum of the element wise multiply 
z

tensor(46)

In [31]:
batch = 32
n, m, p = 10, 20, 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
print(torch.bmm(tensor1, tensor2).shape)    # batch matrix multiply 


torch.Size([32, 10, 30])


# Broadcasting

In [38]:
x1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
x2 = torch.tensor([5, 6]) # expand to the correct matrix size 
z = x1 - x2 
z

tensor([[-4, -4],
        [-2, -2],
        [ 0,  0]])

In [39]:
z = x1 ** x2 
z

tensor([[    1,    64],
        [  243,  4096],
        [ 3125, 46656]])

# operation direction

In [41]:
sum_x = torch.sum(x, dim=0)
print(sum_x)
values, indices = torch.max(x, dim=0)
print(values, indices)
x

tensor(6)
tensor(3) tensor(2)


tensor([1, 2, 3])

In [45]:
sum_dim0 = torch.sum(tensor1, dim=0) # batch direction
print(sum_dim0.shape)
sum_dim1 = torch.sum(tensor1, dim=1) # column direction
print(sum_dim1.shape)
sum_dim2 = torch.sum(tensor1, dim=2) # row direction
print(sum_dim2.shape)

torch.Size([10, 20])
torch.Size([32, 20])
torch.Size([32, 10])


In [48]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t.max(dim=1))
print(torch.argmax(t, dim=1))   # argmax return only indices 

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))
tensor([2, 2])


In [50]:
mean_t = torch.mean(t.float(), dim=0)
print(mean_t)

tensor([2.5000, 3.5000, 4.5000])


In [51]:
z = torch.eq(x, y)
z 

tensor([False, False, False])

In [52]:
torch.sort(y, dim=0, descending=False) # return the values and the indices before

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

In [54]:
z = torch.clamp(torch.rand((3, 3)), min=0.5, max=0.8) # restrict the ceil value and lowest value 
z

tensor([[0.5000, 0.5000, 0.5000],
        [0.7796, 0.8000, 0.5000],
        [0.6831, 0.5000, 0.5440]])

In [56]:
z = torch.all(torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool), dim=0)
z

tensor(False)

In [57]:
z = torch.any(torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool), dim=0)
z

tensor(True)