# Tensor indexing

In [2]:
import torch
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x

tensor([[0.5609, 0.7792, 0.4779, 0.3321, 0.5903, 0.7129, 0.3413, 0.1208, 0.6817,
         0.5428, 0.0648, 0.9794, 0.1558, 0.0787, 0.1417, 0.0169, 0.9653, 0.1761,
         0.0070, 0.9383, 0.5232, 0.7447, 0.8238, 0.1532, 0.6547],
        [0.9850, 0.9422, 0.5337, 0.2954, 0.6960, 0.6632, 0.5087, 0.0882, 0.2189,
         0.1663, 0.7689, 0.9425, 0.1021, 0.5528, 0.4239, 0.1438, 0.4358, 0.4350,
         0.0906, 0.6228, 0.0207, 0.9335, 0.6783, 0.5058, 0.7006],
        [0.1860, 0.3503, 0.7892, 0.0473, 0.6045, 0.2099, 0.5085, 0.8470, 0.7091,
         0.9971, 0.4208, 0.6533, 0.8942, 0.3118, 0.7170, 0.9889, 0.8246, 0.0643,
         0.4696, 0.1621, 0.9242, 0.4048, 0.3974, 0.4933, 0.8011],
        [0.6708, 0.7415, 0.2332, 0.8288, 0.4062, 0.6472, 0.6106, 0.5361, 0.7158,
         0.0244, 0.4792, 0.1980, 0.1849, 0.0618, 0.6239, 0.6386, 0.1551, 0.3141,
         0.6773, 0.7659, 0.4487, 0.3148, 0.7550, 0.0943, 0.3941],
        [0.9304, 0.9394, 0.9105, 0.0211, 0.5543, 0.0378, 0.2977, 0.3154, 0.8003,
       

In [3]:
x.shape

torch.Size([10, 25])

In [4]:
x[:, 0].shape # first feature of all the data

torch.Size([10])

# Fancy indexing 

In [5]:
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

tensor([2, 5, 8])


In [7]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
column = torch.tensor([4, 0])
print(x)
print(x[rows, column]) # pick out elements in the x which regard (rows, column)'s corresponding elements as the indices 

tensor([[0.9049, 0.8154, 0.9963, 0.3348, 0.5955],
        [0.3787, 0.6321, 0.3145, 0.6657, 0.7425],
        [0.0746, 0.0154, 0.5621, 0.3827, 0.3340]])
tensor([0.7425, 0.9049])


In [11]:
x = torch.arange(10)
x[(x < 2) | (x > 8)] # think (x < 2) | (x > 8) as the filter function to get the elements from x

tensor([0, 1, 9])

In [12]:
x[(x < 2) & (x > 8)] # '&' means and here 

tensor([], dtype=torch.int64)

In [13]:
x[x.remainder(2) == 0] # torch.remainder(a, b) == a - a.div(b, rounding_mode="floor") * b

tensor([0, 2, 4, 6, 8])

In [15]:
torch.where(x > 5, x, x * 2) # if condition, first parameter otherwise second one

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [16]:
torch.tensor([1, 2, 2, 3, 3, 3, 4, 4, 4, 4]).unique()

tensor([1, 2, 3, 4])

In [17]:
torch.tensor([10, 10, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4]).unique() # unique will sort the elements first

tensor([ 1,  2,  3,  4, 10])

In [18]:
torch.rand((5, 3, 10)).ndimension() # return the dimension number of the tensor

3

In [19]:
x.numel() # return the number of the elements

10