# Tensor reshaping

In [1]:
import torch 
x = torch.arange(9)

x_3x3 = x.view(3, 3) # act on the continuous memory space, it's a view of the base tensor 
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [2]:
x[0] = -1
x_3x3 # just change the way it interprets the same data, no data movement occurs

tensor([[-1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]])

In [3]:
x.reshape(3, 3)

tensor([[-1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]])

In [5]:
x[0] = 0

In [6]:
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
x_3x3_reshape = x.reshape(3, 3) # create a new data 
x_3x3_reshape.T.view(9)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [10]:
x_3x3_reshape.T.contiguous().view(9) # use contiguous function make a new data which store continuously 

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [13]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape) # cat to connect two tensors
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [16]:
z = x1.view(-1) # flatten the x1 with the parameter value is -1
print(z.shape)
x = torch.rand((32, 20, 10))
print(x.view(32, -1).shape) # flatten part of the dimensions

torch.Size([10])
torch.Size([32, 200])


In [18]:
x.permute(0, 2, 1).shape # change the dimension by the dimension indices 

torch.Size([32, 10, 20])

In [23]:
x = torch.arange(10)
print(x.shape)
print(x.unsqueeze(0)) # 1x10
print(x.unsqueeze(1)) # 10x1
print(x.unsqueeze(0).unsqueeze(1)) # 1x1x10 

torch.Size([10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


the squeeze function is a  little hard to understand